services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '49306:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
